module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '.',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: ['**/*.(t|j)s'],
  coverageDirectory: 'coverage',
  testEnvironment: 'node',
  moduleNameMapper: {
    '^src/(.*)$': '<rootDir>/src/$1',
  },
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/coverage/',
    '/features/',
    '/dist/',
    '/src/config/',
    '/src/core/interceptors/sanitize.interceptor.ts',
    '/src/core/services/logger.service.ts',
    '/src/database/',
    '/src/modules/video',
    '/src/modules/queue',
    'app.module.ts',
    'main.ts',
    '.eslintrc.js',
    'jest.config.js',
    'cucumber.js',
    '/test/',
  ],
  coverageReporters: ['html', 'text', 'lcov'],
};
